### PR TITLE
添加kubeedge扩展插件

### PR DESCRIPTION
**Pull request by zuoxuesong-worker**
Add KubeEdge Extension

### CODE REVIEW

**Review by imneov — APPROVED** [review]

**Comment by benjaminhuo** [comment]
release note section needs to be added at PR description: @zuoxuesong-worker 

```
` ` `release-note
Add KubeEdge Extension
` ` `
```

Also `/lgtm` is needed for the PR to be merged @imneov

**Comment by zuoxuesong-worker** [comment]
Add KubeEdge Extension

**Comment by benjaminhuo** [comment]
image
release note 要这么写，approver `/approve` 和 `/lgtm` 后才可以自动 merge

@zuoxuesong-worker

**Pull request merged**
